package zed.rainxch.core.domain.model.installation

// The one builder the domain tests share for an InstalledApp row: three suites used to carry a
// copy each, so every column added to the model meant three edits that could drift apart. Every
// suite keeps a thin wrapper on top of these defaults for the shape it is about.
fun testInstalledApp(
    packageName: String = "com.example.app",
    installedVersion: String = "1.0.0",
    installedVersionName: String? = "1.0.0",
    installedVersionCode: Long = 100L,
    isUpdateAvailable: Boolean = true,
    isPendingInstall: Boolean = false,
    latestVersion: String? = "2.0.0",
    latestVersionName: String? = latestVersion,
    latestVersionCode: Long? = 200L,
    latestReleasePublishedAt: String? = null,
    pendingInstallFilePath: String? = "/data/parked.apk",
    pendingInstallVersion: String? = if (pendingInstallFilePath != null) "2.0.0" else null,
    pendingInstallAssetName: String? = if (pendingInstallFilePath != null) "app-2.0.0.apk" else null,
    installedAt: Long = 1_000L,
    lastCheckedAt: Long = 2_000L,
    lastUpdatedAt: Long = 1_500L,
    skippedReleaseTag: String? = null,
): InstalledApp = InstalledApp(
    packageName = packageName,
    repoId = 1L,
    repoName = "app",
    repoOwner = "owner",
    repoOwnerAvatarUrl = "https://avatar",
    repoDescription = null,
    primaryLanguage = "Kotlin",
    repoUrl = "https://github.com/owner/app",
    installedVersion = installedVersion,
    installedAssetName = "app-1.0.0.apk",
    installedAssetUrl = "https://dl/app-1.0.0.apk",
    latestVersion = latestVersion,
    latestAssetName = "app-2.0.0.apk",
    latestAssetUrl = "https://dl/app-2.0.0.apk",
    latestAssetSize = 1024L,
    appName = "App",
    installSource = InstallSource.THIS_APP,
    installedAt = installedAt,
    lastCheckedAt = lastCheckedAt,
    lastUpdatedAt = lastUpdatedAt,
    isUpdateAvailable = isUpdateAvailable,
    signingFingerprint = "SHA",
    systemArchitecture = "arm64-v8a",
    fileExtension = "apk",
    isPendingInstall = isPendingInstall,
    installedVersionName = installedVersionName,
    installedVersionCode = installedVersionCode,
    latestVersionName = latestVersionName,
    latestVersionCode = latestVersionCode,
    latestReleasePublishedAt = latestReleasePublishedAt,
    pendingInstallFilePath = pendingInstallFilePath,
    pendingInstallVersion = pendingInstallVersion,
    pendingInstallAssetName = pendingInstallAssetName,
    skippedReleaseTag = skippedReleaseTag,
)
